def on_button_pressed_a():
global strip, ONOFF
strip = neopixel.create(DigitalPin.P1, 1, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 2, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 3, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 4, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 5, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 6, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 7, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 8, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 9, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 10, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 11, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 12, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 13, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 14, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 15, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 16, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 17, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 18, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 19, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 20, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 21, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 22, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 23, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 24, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 25, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 26, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 27, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 28, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 29, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip = neopixel.create(DigitalPin.P1, 30, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
ONOFF = 1
while ONOFF == 1:
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
basic.pause(5)
input.on_button_pressed(Button.A, on_button_pressed_a)

def on_button_pressed_b():
global strip, ONOFF
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 29, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 28, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 27, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 26, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 25, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 24, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 23, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 22, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 21, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 20, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 19, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 18, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 17, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 16, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 15, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 14, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 13, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 12, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 11, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 10, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 9, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 8, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 7, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 6, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 5, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 4, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 3, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 2, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 1, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P1, 0, NeoPixelMode.RGB)
strip.show_color(neopixel.colors(NeoPixelColors.RED))
basic.pause(100)
strip.show_color(neopixel.hsl(0, 0, 0))
ONOFF = 0
input.on_button_pressed(Button.B, on_button_pressed_b)

def on_gesture_shake():
music._play_default_background(music.built_in_playable_melody(Melodies.WAWAWAWAA),
music.PlaybackMode.IN_BACKGROUND)
basic.pause(1000)
music.stop_melody(MelodyStopOptions.ALL)
input.on_gesture(Gesture.SHAKE, on_gesture_shake)

strip: neopixel.Strip = None
ONOFF = 0
ONOFF = 0
strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
strip.show_color(neopixel.hsl(0, 0, 0))
strip = neopixel.create(DigitalPin.P0, 0, NeoPixelMode.RGB)